name: Build wheel (composite)
description: Builds wheels for PTE Adapter for Model Explorer

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python environment
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Checkout plugin repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build plugin package
      shell: bash
      run: |
        python -m pip install build
        python -m build

    - name: Upload plugin package artifact
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: dist
        path: dist
